### ISSUE TITLE
Problems with applying qml to osm spatiatialite-layers

### ISSUE THREAD

**Issue by koenigherford** [anitagraser/QGIS-resources#12] opened 2017-09-13 09:37 UTC
I've downloaded osm data and converted it to spatialite-layers with qgis 2.18.11. - build-in vector-openstreetmap-plugin. 

Importing your various styles to the point/polygon/line-layers gave every time the error
"unexpected character in line 42 column 91"

![grafik](https://user-images.githubusercontent.com/28433436/30370228-3f7199d0-9877-11e7-93f7-897b82cd8b86.png)

What may be wrong ?

**Comment by anitagraser** [comment] 2017-09-13 10:12
Duplicate of https://github.com/anitagraser/QGIS-resources/issues/5

**Closed by anitagraser** 2017-09-13 10:12 UTC
